### ISSUE TITLE
Unable to forward to roms with spaces in the filenames.

### ISSUE THREAD

**Issue by jamesloosli** [rlaphoenix/nton#10]
**Describe the bug**
When creating a forwarder to a rom with retroarch, spaces in the rom filename would cause the forwarder to boot the selected retroarch core with an error message; "File at /some/path/to/rom" not found for a rom at `/some/path/to/rom\ file\ path\ with\ spaces`.

**To Reproduce**
Create a forwarder with a command similar to;

```
nton build -n "MegaMan Zero" \
  RetroArch/retroarch/cores/mgba_libretro_libnx.nro \
  --sdmc /retroarch/cores/mgba_libretro_libnx.nro \
  --rom "/roms/gba/Megaman\ Zero\ \(USA,\ Europe\).zip" \
 ```

**Expected behavior**
I should be able to create forwarders for roms with spaces in the filenames.

If I just need to double-escape the spaces or something, that just needs to be in the documentation for the project somewhere.

**Additional context**
Love the project, super grateful you put this together.

**Comment by rlaphoenix** [comment]
Does it not work if you do the same command, without a `\ `. Just ` `. You just need to make sure the path is encapsulated with quotes. What you put I think confuses the forwarder rom into looking for the rom at `/roms/gba/Megaman/ Zero/ /(USA,/ Europe/).zip`. I could be wrong, but that's my best guess here.

**Comment by brx** [comment]
https://github.com/rlaphoenix/nton/blob/f63ca91024ef07192b1ca8e205625032c46a4438/nton/main.py#L310

may need to be `next_argv += f" \"sdmc:{rom}\""`. that works for me.

**Comment by rlaphoenix** [comment]
> https://github.com/rlaphoenix/nton/blob/f63ca91024ef07192b1ca8e205625032c46a4438/nton/main.py#L310
> 
> may need to be `next_argv += f" \"sdmc:{rom}\""`. that works for me.

Nice find, that looks about right. Feel free to make a PR, but do `f' "sdmc:{rom}"'`
