### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by Finnlikecookies** [rlaphoenix/nton#11]
**Describe the bug**
When i start the installed .nsp it crashes.
**To Reproduce**
Place an nro with the name coolgame.nro in the switch folder on the sd card.
Mount the switch sd card as F:
Use the command:
nton build --name CoolGame --publisher ThatFinn --version 0.0.1 F:/switch/coolgame.nro
Install the nsp
Start the game
crash

**Expected behavior**
The application to start
 
**Screenshots**

**Additional context**
The working directory was C:\Users\<myuser>\.switch

**Comment by rlaphoenix** [comment]
Have you followed the troubleshooting steps? Specifically [this one](https://github.com/rlaphoenix/nton#the-forwarder-does-not-launch-the-software-was-closed-because-an-error-occurred)?

**Comment by Finnlikecookies** [comment]
I've done both things and I made a new nsp file but the issue persists

**Comment by rlaphoenix** [comment]
What firmware version are you on, and are you on emuMMC or SysMMC? Which version of Atmosphere are you on?

**Comment by Finnlikecookies** [comment]
I'm on SysMMC, Atmosphere 1.4.1 and Firmware 15.0.1 but i managed to figure out how to fix it. I've looked at the crash reports and the process name was "Retroarch F". I believe the F means Forwarder so I believe for some reason nton thinks the nro file is a retroarch rom so I added --sdmc /switch/coolgame.nro to the building process and that fixed the issue

**Comment by rlaphoenix** [comment]
That seems quite strange because --sdmc in your case would have received the exact same result. Is that definitely the only difference between the two NSPs and two times you installed? You didn't change anything else on your system?

**Comment by Finnlikecookies** [comment]
After it failed i've tried it with no argumens (before I had the arguments:  --name CoolGame --publisher ThatFinn --version 0.0.1 F:/switch/coolgame.nro) but that didn't work either. Later had a look at the logs and tried it with --sdmc and that fixed the issue.  That was the ONLY change i made

**Comment by Finnlikecookies** [comment]
sorry that I've written it unclear but the final command was `nton build F:/switch/coolgame.nro --sdmc /switch/coolgame.nro` (I didn't use --name, --publisher and --version because I've just set those parameters in the source code of my game before I compiled)
