### ISSUE TITLE
prod.keys is missing, but it's not.

### ISSUE THREAD

**Issue by admiralspeedy** [rlaphoenix/nton#13]
**Describe the bug**
I installed nton with pip (Python 3.10) and when I try to run it, it tells me that prod,keys is missing in my C:\Users\Name\\.switch folder, but it's there with the latest keys. 

I can literally copy the path it outputs and it opens my prod.keys in Notepad++ and the file was pulled using Lockpick on my own Switch.

**To Reproduce**
1. Install with pip
2. Run nton
3. See error

**Expected behavior**
It should find my prod.keys file.

**Comment by admiralspeedy** [comment]
Just want to note that after posting this I tried by cloning the repo and running with poetry and it works fine.

**Comment by rlaphoenix** [comment]
Is the error you are getting exactly `!! prod.keys is missing! Please place it in the current working directory or at "C:\Users\Name\.switch\prod.keys"`? (barring the `Name` substitution)

The code here checks if there's a valid file at that location, which if not it errors. It's kind of strange if it is in fact the right path it's failing to find, and yet it exists.

**Comment by admiralspeedy** [comment]
> Is the error you are getting exactly `!! prod.keys is missing! Please place it in the current working directory or at "C:\Users\Name\.switch\prod.keys"`? (barring the `Name` substitution)
> 
> The code here checks if there's a valid file at that location, which if not it errors. It's kind of strange if it is in fact the right path it's failing to find, and yet it exists.

Yes, that is the exact error and my prod.leys file is there. I can literally copy the path from the error and open the file.

The same issue does not happen if I run nton with poetry by cloning the repo. It finds the key file without issue.

**Comment by rlaphoenix** [comment]
I see the mistake. This is something I should have spotted a bit faster considering your diagnosis of it working via local git clone'd install. Lol.

Basically, it is already patched in the code, but the release on PyPI is outdated. I haven't released a new version with that bug fixed yet because I intended to have the new ExeFS rom tested and more-or-less forgot about it and worked on my other projects.

I will consider this fixed, since it's not an issue.

**Comment by admiralspeedy** [comment]
Can you do a build with the new ExeFS ROM so I can test it?

I opened another issue because no matter what I do, the resulting NSP does not launch for me, but your prebuilt ones do so I'm not sure what I could be doing wrong.
