### ISSUE TITLE
"é" character causing broken names

### ISSUE THREAD

**Issue by 0ver-flow** [rlaphoenix/nton#22]
**Describe the bug**

When using the character "é" in titles (i.e. Pokémon FireRed Version) the character gets changed or mistranslated during the process. In NxFileViewer it appears as so:
![Screenshot 2023-10-01 231728](https://github.com/rlaphoenix/nton/assets/1626853/bc9dbd41-7df1-473f-968a-214f155aff0a)
And on the Switch:
![2023100123172800](https://github.com/rlaphoenix/nton/assets/1626853/e8805c83-92c5-47ed-87f7-d8c0d32950f2)
Not pictured here - sometimes the titles will corrupt and include text from other installed titles.

**To Reproduce**

1. Install using `pip install nton`
2. Run `nton build "G:/retroarch/cores/mgba_libretro_libnx.nro" -n "Pokémon FireRed Version" -p "Nintendo" -v 1.0 -i "C:/Users/<User>/Downloads/pfr.jpg" --id 0740192E63E62000 --rom "/roms/gba/Pokemon - FireRed Version.gba"`
3. Check in NxFileViewer or install to Switch

**Expected behavior**

Using other forwarder generators this can be accomplished. With https://nsp-forwarder.n8.io/
![Screenshot 2023-10-01 232602](https://github.com/rlaphoenix/nton/assets/1626853/9376952f-18fd-4cf8-8d92-c764a80e11bc)
![image](https://github.com/rlaphoenix/nton/assets/1626853/5bc02d5e-035e-419e-b7ca-15aaee01fde1)
Even doing it manually with HacBrewPack is possible, though it seems to have its own issues with including quotation marks.

**Comment by rlaphoenix** [comment]
Turned out to be a HacBrewPack issue, but also brought to light another issue which is now also squashed.
