### ISSUE TITLE
Question: where did you get exefs files?

### ISSUE THREAD

**Issue by acheronfail** [rlaphoenix/nton#31]
I'm playing around with writing a similar tool for this kind of thing, and am wondering where you got the `exefs` files located here: https://github.com/rlaphoenix/nton/tree/master/nton/assets/exefs ?

Is there some way to generate these files? Looks like they're [the main binary](https://switchbrew.org/wiki/ExeFS) that the Switch runs...

**Comment by rlaphoenix** [comment]
This is the Forwarder rom, the actual switch-application code that is run. It is basically just a minimum-required application that launches an applet based on it's location on SD card.

It is a pre-compiled build of one of the versions here: https://github.com/Skywalker25/Forwarder-Mod though I don't know which. I was given the build by the person of this repo on GBATemp through PM.
